### ISSUE TITLE
Metadata supporting data formats being sold short

### ISSUE THREAD

**Issue by hlapp** [weecology/data-sharing-paper#135]
In the section about data formats, I agree that FASTA and Newick are widely supported by tools. But I question whether that really means that they are also the best recommendation for formats in which to archive data for perpetuity. It is formats like these in particular that focus on representing the data only, and have little to practically no provisions for attaching metadata, structured or not. As a result, various ad-hoc ways of formatting comments (for the case Newick, the stuff enclosed in square brackets) or description text (such as the text following the '>' in FASTA) have been devised, with little or fragile standards governing them and corresponding issues arising from that (is the value in square brackets in Newick a branch length, branch support, or node label?).

While undeniably there are few programs right now that understand or produce metadata-aware formats such as PhyloXML or NeXML, I feel like completely ignoring these and the problems that led to them is a missed opportunity in this paper, especially given the attention devoted to metadata earlier in the text. It would seem to perpetuate this notion that metadata and data are separate, separable, and that they can be clearly delineated, and that in the end of the day it's the data that matters, when in reality metadata can quickly become data, and can be absolutely crucial in determining fitness for (re)use of a data item.

**Comment by ethanwhite** [comment]
Thanks for the feedback Hilmar. While I certainly agree with you (and @cboettig) about this general idea I don't believe that this is the place to discuss it. This paper is intentionally designed as an introduction to these ideas for people who haven't really thought about them at all - the folks collecting, preserving, and potentially sharing most of the data in EEB. In our (the authors) collective opinion (and we've discussed this a lot) trying to introduce this level of idea would actually result in the paper having less of an impact by making the topic seem overwhelming and confusing, and therefore leading the intended audience to just give up on pursuing better data practices. In #71 and in the [response to review](https://github.com/weecology/data-sharing-paper/blob/master/response_to_review.md) we've discussed some of this philosophy in more detail. In short, I'd rather see lots of people improving their data to the point where it can be worked with or salvaged than a handful of people producing perfect data. Once we get everyone doing the basics right then it will be more productive to try to introduce things like XML so that we move towards broader adoption of these kinds of standards.

**Comment by cboettig** [comment]
I see your point entirely.  Asking users to adopt XML based formats that are not supported by the software they are using is futile.  Your paper does a great job convincing readers that things like licenses and formats matter, which is fantastic.  

I think the "XML-free" approach actually puts a substantially greater burden on users than fully supported XML metadata standard would.  The user -- who as you say has never thought of these issues before -- is forced to manually and laboriously address them each time (or ignore them).  Remember to declare the right missing value character.  Manually do quality control with tricks like summing the columns.  Remember to declare a license, remember to declare column values.  No automated tools will help the user fill out this information. No tools will help another user extract this information when they want to re-use the dataset.  

I completely agree with @hlapp that the problem is a lack of community-adopted tools to work with the XML. With the right tools, these formats should be much easier, not harder, for inexperienced researchers to handle.  Microsoft `.docx` is an XML-based data structure -- no one complains they don't use Word because XML is too difficult.  With the right tools, this becomes easy to do, and easy to extend.  No more "do I have to `melt` the table first?  Do I have to sum the columns as a quality-control?  Are my date in ISO1806 format?  etc etc...

Only -- we're not there yet.  So given the current state things, your manuscript hits the nail on the head.  (Hopefully by 2014 we'll have NeXML and EML support for R at least....)

**Comment by hlapp** [comment]
I was going to let this rest, but given the rather unfortunate direction this thread seems to be going, and the possibility that I'm at fault for this by not clearly expressing myself, I'll try to clarify. My intent by no means was to recommend to users to use XML formats that are poorly supported by tools. My principle point is rather entirely independent of XML. Even Genbank format is vastly more expressive for metadata than FASTA, and it is not XML. NEXUS allows hugely more metadata than does Newick, and it is not XML. Both formats are widely supported by tools, even if perhaps a little less widely than FASTA and Newick. In your manuscript you just happened to chose those formats that are by far the most inviting to stripping away all metadata, or to provide them in some ad-hoc way with poor interoperability. In this I feel the paper is self-contradicting: In other places it advocates to document column or row labels and other metadata for spreadsheets - if this is important for spreadsheet data, surely documenting metadata is important for sequence and phylogenetic data as well?

Second, I contend that better formats become adopted not by hope and waiting around, but by end-user demand. (@cboettig: many users wanted interoperability between MS Office and the Open Office standard. I don't think we'd have .docx otherwise.) This is what I mean by missed opportunity - if you aren't even letting people know that these other efforts and formats exist and why they might matter, it's a missed opportunity to allow people to know that they could promote consideration and adoption to tool developers in their domain.

Third, I contend that between not mentioning these issues at all, and recommending users to try to use better but presently poorly supported formats, that middle ground is possible that would be appropriate even for the audience targeted here. This may not be more than a sentence or two, but what I was trying to suggest is that having those may still be much better than just recommending FASTA and Newick as best practice for sequence and phylogeny data.

Anyhow, I'll rest my argument there.

**Comment by cboettig** [comment]
@ethanwhite I also don't mean to drag this on with respect to the paper,
though I like Hilmar's "middle ground" of pointing out that formats that
are more expressive for metadata will ease the users burden (e.g. just use
nexus instead of writing a readme saying brackets are branch lengths...)  I
carry on the discussion below for my academic edification only.

@hilmar Thanks for the clarifications.  I referred to XML-based formats
only as shorthand, of course it doesn't matter if they are XML or not, but
if they have (machine-readable) metadata.  I see your point about NEXUS
etc, but I'm sure we'd agree that it's actually not about the filetype at
all, it's really a matter of having good metadata, yes?    e.g. in
principle one could accomplish the same thing with an EML annotated newick
tree (or simply an adequate README?) as with a nexus or nexml tree... no
need to pick favorite formats -- though certainly some will be easier to
use than others.  Once a user faces the burden of 'manually' managing the
metadata, the reason to use a format that supports it naturally might
become self-evident?

I also like your point about end-user demand, though I was only trying to
say that teaching people to use metadata formats shouldn't be equated with
teaching them XML.  (notwithstanding Terence Parr, "being an expert in XML
is like being an expert in CSV").   I would love to see more end-user
demand for these tools, and in many ways I think @ethanwhite's paper moves
us to them.  If we don't document metadata at all, we don't realize we need
better tools.  As we start to share data and run into these problems,
sooner or later more of us will think: "Wouldn't it be nice to have a tool
to fill out this metadata in a standard way, and check for consistency, etc
etc?

As for waiting around, you know that's not my style ;-)  In part thanks to
@ethanwhite's apt comments that hardly anyone uses EML I started writing
`reml` for R, https://github.com/ropensci/reml , since R's native data
structures have lots of metadata that is lost when writing out to files
(the same could be said of tree formats).  And of course we have NESCENT's
Google Summer of Code student writing a Nexus parser for R, for which I
think there is already community demand.

Thanks both for a valuable discussion on this!

On Sat, Jul 6, 2013 at 12:02 PM, Hilmar Lapp notifications@github.comwrote:

> I was going to let this rest, but given the rather unfortunate direction
> this thread seems to be going, and the possibility that I'm at fault for
> this by not clearly expressing myself, I'll try to clarify. My intent by no
> means was to recommend to users to use XML formats that are poorly
> supported by tools. My principle point is rather entirely independent of
> XML. Even Genbank format is vastly more expressive for metadata than FASTA,
> and it is not XML. NEXUS allows hugely more metadata than does Newick, and
> it is not XML. Both formats are widely supported by tools, even if perhaps
> a little less widely than FASTA and Newick. In your manuscript you just
> happened to chose those formats that are by far the most inviting to
> stripping away all metadata, or to provide them in some ad-hoc way with
> poor interoperability. In this I feel the paper is self-contradicting: In
> other places it advocates to document column or row labels and other
> metadata for spreadsheets - if this is impo rtant for spreadsheet data,
> surely documenting metadata is important for sequence and phylogenetic data
> as well?
> 
> Second, I contend that better formats become adopted not by hope and
> waiting around, but by end-user demand. (@cboettighttps://github.com/cboettig:
> many users wanted interoperability between MS Office and the Open Office
> standard. I don't think we'd have .docx otherwise.) This is what I mean by
> missed opportunity - if you aren't even letting people know that these
> other efforts and formats exist and why they might matter, it's a missed
> opportunity to allow people to know that they could promote consideration
> and adoption to tool developers in their domain.
> 
> Third, I contend that between not mentioning these issues at all, and
> recommending users to try to use better but presently poorly supported
> formats, that middle ground is possible that would be appropriate even for
> the audience targeted here. This may not be more than a sentence or two,
> but what I was trying to suggest is that having those may still be much
> better than just recommending FASTA and Newick as best practice for
> sequence and phylogeny data.
> 
> Anyhow, I'll rest my argument there.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/weecology/data-sharing-paper/issues/135#issuecomment-20559118
> .

## 

Carl Boettiger
UC Santa Cruz
http://carlboettiger.info/

**Comment by ethanwhite** [comment]
Sorry to be so slow getting back to both of you on these really valuable and interesting points. The paper had already been resubmitted/accepted when this came up and travel, ESA, moving for sabbatical, yada, yada, yada.

Thanks for the very useful clarification @hlapp . I am in the process of swapping out FASTA for Genbank and Nexus for Newick in the proofs. I am also adding the following extension to the metadata section "Metadata can take several forms, including descripttive file and column names, a written description of the data, images (i.e., maps, photographs), and specially structured information that can be read by computers (i.e., machine readable metadata) _that is sometimes directly incorporated into the data files themselves (e.g., PhyloXML)_."

Hopefully this will help at least hint at the general point that data and metadata are not necessarily distinct and avoid recommending the less desirable formats.
