### ISSUE TITLE
Clarify that "Excel format" means .xls and .xlsx

### ISSUE THREAD

**Issue by ethanwhite** [weecology/data-sharing-paper#74]
From JE:

Dan Hocking:

> On line 129 you mention MS Excel format. Excel files can be saved as .csv files. It might be worth putting “(.xls, .xlsx)” parenthetically after Excel so people don’t think that excel files saved as .csv are a major problem.

**Comment by embaldridge** [comment]
Done.  Used e.g. instead of i.e. because .xls and .xlsx are examples of the types of files that are program specific, and Excel could come up with new file extensions in the future.

**Comment by brymz** [comment]
With this comment, maybe it's worth reconsidering also adding the Quatro
pro extension .qpw.

**Comment by ethanwhite** [comment]
Yeah, didn't someone mention at some point that Quatro pro is more more common in Europe? If it's being used regularly somewhere then I like the idea of generalizing this sentence by including it.

**Comment by embaldridge** [comment]
What is Quatro pro?

**Comment by brymz** [comment]
It's Corel's version of excel. http://en.wikipedia.org/wiki/Quattro_Pro

**Comment by embaldridge** [comment]
Okay.  While we are at it, why don't we add Open Office .ods as well?

In contrast to plain text files, proprietary formats (e.g,  Microsoft Excel, .xls, .xlsx; Open Office Calc, .ods; Quattro Pro, .qpw) can be difficult to load into other programs.

**Comment by brymz** [comment]
Is Open Office proprietary?

**Comment by embaldridge** [comment]
I don't really think so, but there are problems opening that file extension
up with other spreadsheet software, so I think it warrants a mention as an
example of "file extensions not to use".

**Comment by sarahsupp** [comment]
People use Corel? :)
If so, then I'm in favor of it going in, as long as our list doesn't get too long and bulky.

**Comment by embaldridge** [comment]
So, add, or not add?  I was thinking about this, and it might be better to focus on what formats to use, rather than listing all the formats not to use.  I think that the Excel formats are a good example, because I think that even if people do not use Microsoft Excel, they are probably familiar with it.  I am happy with leaving it just as Excel, but making sure that the recommendation for .csv or, secondarily, tab delimiting is strong.  However, I don't really have a strong opinion on this either way, and am happy to do whatever the group wants.

**Comment by ethanwhite** [comment]
I agree with Elita, but again it's not a strong feeling so if someone has a real opinion on this that's OK with me.
