### ISSUE TITLE
Suggested additions to section 6

### ISSUE THREAD

**Issue by ethanwhite** [weecology/data-sharing-paper#96]
Carl Boettiger (#71):

> A good section in principle, but not very concrete. It sounds like your primary advice here is to avoid undefined abbreviations, and to include columns with generic information like species or lat/long coordinates that might be useful to others. In both cases, you appear to be citing issues that have more to do with metadata. E.g. if I collect all my data on a single species at a single geographic site; is it really necessary that I add columns for species and lat-long, rather than define this information in the metadata?
> 
> I think more helpful here would be to emphasize the value of collecting/recording additional generic data even if it is not relevant for your study. (Researchers not interested in spatial or seasonal patterns do not always report spatial coordinates or sampling dates and times, temperature/weather information, gross measurements of sampled individuals like length and mass etc.)

**Comment by sarahsupp** [comment]
I suppose all of our points in some way link to good metadata, i.e., if you follow strict metadata standards, you should be doing all of these things. If you do all of these things, writing any kind of metadata should be easier. 

I think Carl's point highlights this connection, which is important and useful, but I'm not sure that it's exactly what we had in mind. I think we were mainly trying to say that the data you collect should be defined (avoid abbreviations/codes) rather than that you need to include a lot of other extraneous info.

**Comment by ethanwhite** [comment]
Group Discussion:

Emphasize that if you have extra data that it's helpful to provide it, but don't try to convince folks to collect addition data as this could come off wrong.

**Comment by ethanwhite** [comment]
This is currently being addressed in #119. I don't think it's quite there yet, but any associated work should build on it as it's definitely a step in the right direction.
